                        <div class="spoiler_links"> 
                            <h2>Сольные восточные костюмы (Альбом 1)</h2>
                        </div>
                        <div class="spoiler_body"> 
                            <div id="gallerybellydancesolo1" style="display:none;">
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-1-2.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-1-2.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-1-1.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-1-1.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>                                
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-1-32.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-1-32.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-1-33.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-1-33.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                                
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-1-3.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-1-3.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-1-6.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-1-6.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-1-7.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-1-7.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-1-8.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-1-8.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-1-11.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-1-11.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                                
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-1-5.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-1-5.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-1-4.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-1-4.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>                                
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-1-10.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-1-10.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-1-9.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-1-9.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                                
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-1-12.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-1-12.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                                
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-1-13.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-1-13.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-1-14.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-1-14.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                                
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-1-15.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-1-15.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-1-19.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-1-19.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-1-16.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-1-16.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-1-17.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-1-17.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-1-18.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-1-18.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-1-20.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-1-20.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-1-21.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-1-21.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-1-22.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-1-22.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                                
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-1-27.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-1-27.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-1-26.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-1-26.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-1-23.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-1-23.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-1-24.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-1-24.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-1-25.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-1-25.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>

                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-1-28.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-1-28.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                                
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-1-29.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-1-29.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-1-30.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-1-30.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-1-31.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-1-31.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                            </div> 
                        </div> <!-- spoiler_body -->                   
                        <script type="text/javascript">
                            jQuery(document).ready(function(){
                                jQuery("#gallerybellydancesolo1").unitegallery({
                                    carousel_space_between_tiles: 10,        /*space between tiles - расстояние между фотками в галерее*/
                                    carousel_autoplay: true,
                                    carousel_padding: 8,     
                                    tile_border_width: 4, /*толщина рамки в галерее*/
                                    tile_border_color:"#fff",    /*цвет рамки в галерее*/ 
                                });
                            });
                        </script>  