                <div class="spoiler_links"> 
                    <h2>Купальники для художественной гимнастики</h2>
                </div>
                <div class="spoiler_body"> 
                    <div id="galleryart-gymnastics" style="display:none;">
                    
                        <a href="http://alinavgusarova.ru/">        <img alt="Купальник для художественной гимнастики"        src="http://alinavgusarova.ru/images/gallery/thumbs/art-gymnastics-26.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/art-gymnastics-26.jpg"        data-description="Купальники для художественной гимнастики"        style="display:none">        </a>
                        <a href="http://alinavgusarova.ru/">        <img alt="Купальник для художественной гимнастики"        src="http://alinavgusarova.ru/images/gallery/thumbs/art-gymnastics-27.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/art-gymnastics-27.jpg"        data-description="Купальники для художественной гимнастики"        style="display:none">        </a>
                        <a href="http://alinavgusarova.ru/">        <img alt="Купальник для художественной гимнастики"        src="http://alinavgusarova.ru/images/gallery/thumbs/art-gymnastics-28.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/art-gymnastics-28.jpg"        data-description="Купальники для художественной гимнастики"        style="display:none">        </a>

                        <a href="http://alinavgusarova.ru/">        <img alt="Купальник для художественной гимнастики"        src="http://alinavgusarova.ru/images/gallery/thumbs/art-gymnastics-23.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/art-gymnastics-23.jpg"        data-description="Купальники для художественной гимнастики"        style="display:none">        </a>
                        <a href="http://alinavgusarova.ru/">        <img alt="Купальник для художественной гимнастики"        src="http://alinavgusarova.ru/images/gallery/thumbs/art-gymnastics-24.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/art-gymnastics-24.jpg"        data-description="Купальники для художественной гимнастики"        style="display:none">        </a>
                        <a href="http://alinavgusarova.ru/">        <img alt="Купальник для художественной гимнастики"        src="http://alinavgusarova.ru/images/gallery/thumbs/art-gymnastics-25.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/art-gymnastics-25.jpg"        data-description="Купальники для художественной гимнастики"        style="display:none">        </a>                        
                    
                        <a href="http://alinavgusarova.ru/">        <img alt="Купальник для художественной гимнастики"        src="http://alinavgusarova.ru/images/gallery/thumbs/art-gymnastics-18.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/art-gymnastics-18.jpg"        data-description="Купальники для художественной гимнастики"        style="display:none">        </a>
                        <a href="http://alinavgusarova.ru/">        <img alt="Купальник для художественной гимнастики"        src="http://alinavgusarova.ru/images/gallery/thumbs/art-gymnastics-30.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/art-gymnastics-30.jpg"        data-description="Купальники для художественной гимнастики"        style="display:none">        </a>
                        <a href="http://alinavgusarova.ru/">        <img alt="Купальник для художественной гимнастики"        src="http://alinavgusarova.ru/images/gallery/thumbs/art-gymnastics-31.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/art-gymnastics-31.jpg"        data-description="Купальники для художественной гимнастики"        style="display:none">        </a>                    
                    
                        <a href="http://alinavgusarova.ru/">        <img alt="Купальник для художественной гимнастики"        src="http://alinavgusarova.ru/images/gallery/thumbs/art-gymnastics-1.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/art-gymnastics-1.jpg"        data-description="Купальники для художественной гимнастики"        style="display:none">        </a>
                        <a href="http://alinavgusarova.ru/">        <img alt="Купальник для художественной гимнастики"        src="http://alinavgusarova.ru/images/gallery/thumbs/art-gymnastics-2.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/art-gymnastics-2.jpg"        data-description="Купальники для художественной гимнастики"        style="display:none">        </a>
                        <a href="http://alinavgusarova.ru/">        <img alt="Купальник для художественной гимнастики"        src="http://alinavgusarova.ru/images/gallery/thumbs/art-gymnastics-3.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/art-gymnastics-3.jpg"        data-description="Купальники для художественной гимнастики"        style="display:none">        </a>
                        
                        <a href="http://alinavgusarova.ru/">        <img alt="Купальник для художественной гимнастики"        src="http://alinavgusarova.ru/images/gallery/thumbs/art-gymnastics-14.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/art-gymnastics-14.jpg"        data-description="Купальники для художественной гимнастики"        style="display:none">        </a>
                        <a href="http://alinavgusarova.ru/">        <img alt="Купальник для художественной гимнастики"        src="http://alinavgusarova.ru/images/gallery/thumbs/art-gymnastics-15.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/art-gymnastics-15.jpg"        data-description="Купальники для художественной гимнастики"        style="display:none">        </a>                        
                        <a href="http://alinavgusarova.ru/">        <img alt="Купальник для художественной гимнастики"        src="http://alinavgusarova.ru/images/gallery/thumbs/art-gymnastics-4.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/art-gymnastics-4.jpg"        data-description="Купальники для художественной гимнастики"        style="display:none">        </a>
                        <a href="http://alinavgusarova.ru/">        <img alt="Купальник для художественной гимнастики"        src="http://alinavgusarova.ru/images/gallery/thumbs/art-gymnastics-5.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/art-gymnastics-5.jpg"        data-description="Купальники для художественной гимнастики"        style="display:none">        </a>
                        <a href="http://alinavgusarova.ru/">        <img alt="Купальник для художественной гимнастики"        src="http://alinavgusarova.ru/images/gallery/thumbs/art-gymnastics-6.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/art-gymnastics-6.jpg"        data-description="Купальники для художественной гимнастики"        style="display:none">        </a>
                        
                        <a href="http://alinavgusarova.ru/">        <img alt="Купальник для художественной гимнастики"        src="http://alinavgusarova.ru/images/gallery/thumbs/art-gymnastics-7.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/art-gymnastics-7.jpg"        data-description="Купальники для художественной гимнастики"        style="display:none">        </a>
                        <a href="http://alinavgusarova.ru/">        <img alt="Купальник для художественной гимнастики"        src="http://alinavgusarova.ru/images/gallery/thumbs/art-gymnastics-8.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/art-gymnastics-8.jpg"        data-description="Купальники для художественной гимнастики"        style="display:none">        </a>
                        <a href="http://alinavgusarova.ru/">        <img alt="Купальник для художественной гимнастики"        src="http://alinavgusarova.ru/images/gallery/thumbs/art-gymnastics-9.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/art-gymnastics-9.jpg"        data-description="Купальники для художественной гимнастики"        style="display:none">        </a>
                        <a href="http://alinavgusarova.ru/">        <img alt="Купальник для художественной гимнастики"        src="http://alinavgusarova.ru/images/gallery/thumbs/art-gymnastics-10.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/art-gymnastics-10.jpg"        data-description="Купальники для художественной гимнастики"        style="display:none">        </a>
                        <a href="http://alinavgusarova.ru/">        <img alt="Купальник для художественной гимнастики"        src="http://alinavgusarova.ru/images/gallery/thumbs/art-gymnastics-11.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/art-gymnastics-11.jpg"        data-description="Купальники для художественной гимнастики"        style="display:none">        </a>
                        <a href="http://alinavgusarova.ru/">        <img alt="Купальник для художественной гимнастики"        src="http://alinavgusarova.ru/images/gallery/thumbs/art-gymnastics-12.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/art-gymnastics-12.jpg"        data-description="Купальники для художественной гимнастики"        style="display:none">        </a>
                        <a href="http://alinavgusarova.ru/">        <img alt="Купальник для художественной гимнастики"        src="http://alinavgusarova.ru/images/gallery/thumbs/art-gymnastics-13.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/art-gymnastics-13.jpg"        data-description="Купальники для художественной гимнастики"        style="display:none">        </a>
                        <a href="http://alinavgusarova.ru/">        <img alt="Купальник для художественной гимнастики"        src="http://alinavgusarova.ru/images/gallery/thumbs/art-gymnastics-17.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/art-gymnastics-17.jpg"        data-description="Купальники для художественной гимнастики"        style="display:none">        </a>
                        <a href="http://alinavgusarova.ru/">        <img alt="Купальник для художественной гимнастики"        src="http://alinavgusarova.ru/images/gallery/thumbs/art-gymnastics-19.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/art-gymnastics-19.jpg"        data-description="Купальники для художественной гимнастики"        style="display:none">        </a>
                        <a href="http://alinavgusarova.ru/">        <img alt="Купальник для художественной гимнастики"        src="http://alinavgusarova.ru/images/gallery/thumbs/art-gymnastics-20.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/art-gymnastics-20.jpg"        data-description="Купальники для художественной гимнастики"        style="display:none">        </a>
                        <a href="http://alinavgusarova.ru/">        <img alt="Купальник для художественной гимнастики"        src="http://alinavgusarova.ru/images/gallery/thumbs/art-gymnastics-21.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/art-gymnastics-21.jpg"        data-description="Купальники для художественной гимнастики"        style="display:none">        </a>
                        <a href="http://alinavgusarova.ru/">        <img alt="Купальник для художественной гимнастики"        src="http://alinavgusarova.ru/images/gallery/thumbs/art-gymnastics-22.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/art-gymnastics-22.jpg"        data-description="Купальники для художественной гимнастики"        style="display:none">        </a>
                        <a href="http://alinavgusarova.ru/">        <img alt="Купальник для художественной гимнастики"        src="http://alinavgusarova.ru/images/gallery/thumbs/art-gymnastics-16.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/art-gymnastics-16.jpg"        data-description="Купальники для художественной гимнастики"        style="display:none">        </a>
                        <a href="http://alinavgusarova.ru/">        <img alt="Купальник для художественной гимнастики"        src="http://alinavgusarova.ru/images/gallery/thumbs/art-gymnastics-29.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/art-gymnastics-29.jpg"        data-description="Купальники для художественной гимнастики"        style="display:none">        </a>
                    </div> 
                </div> <!-- spoiler_body -->                   
                <script type="text/javascript">
                    jQuery(document).ready(function(){
                        jQuery("#galleryart-gymnastics").unitegallery({
                            carousel_space_between_tiles: 10,        /*space between tiles - расстояние между фотками в галерее*/
                            carousel_autoplay: true,
                            carousel_padding: 8, 
                            theme_navigation_margin: 2, /*расстояние между фото и навигацией*/      
                            tile_border_width: 4, /*толщина рамки в галерее*/
                            tile_border_color:"#fff",    /*цвет рамки в галерее*/ 
                        });
                    });
                </script>         