                        <div class="spoiler_links"> 
                            <h2>Групповые восточные костюмы</h2>
                        </div>
                        <div class="spoiler_body"> 
                            <div id="gallerybellydancegroup" style="display:none;">
                                
                                <a href="http://alinavgusarova.ru/">        <img alt="Групповые восточные костюмы"             src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-group-15.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-group-15.jpg"                 data-description="Групповые восточные костюмы"         style="display:none">                </a>                    
                                <a href="http://alinavgusarova.ru/">        <img alt="Групповые восточные костюмы"             src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-group-3.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-group-3.jpg"                 data-description="Групповые восточные костюмы"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Групповые восточные костюмы"             src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-group-4.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-group-4.jpg"                 data-description="Групповые восточные костюмы"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Групповые восточные костюмы"             src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-group-5.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-group-5.jpg"                 data-description="Групповые восточные костюмы"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Групповые восточные костюмы"             src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-group-6.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-group-6.jpg"                 data-description="Групповые восточные костюмы"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Групповые восточные костюмы"             src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-group-7.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-group-7.jpg"                 data-description="Групповые восточные костюмы"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Групповые восточные костюмы"             src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-group-8.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-group-8.jpg"                 data-description="Групповые восточные костюмы"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Групповые восточные костюмы"             src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-group-10.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-group-10.jpg"                 data-description="Групповые восточные костюмы"         style="display:none">                </a>
                                
                                <a href="http://alinavgusarova.ru/">        <img alt="Групповые восточные костюмы"             src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-group-35.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-group-35.jpg"                 data-description="Групповые восточные костюмы"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Групповые восточные костюмы"             src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-group-36.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-group-36.jpg"                 data-description="Групповые восточные костюмы"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Групповые восточные костюмы"             src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-group-44.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-group-44.jpg"                 data-description="Групповые восточные костюмы"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Групповые восточные костюмы"             src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-group-38.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-group-38.jpg"                 data-description="Групповые восточные костюмы"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Групповые восточные костюмы"             src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-group-39.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-group-39.jpg"                 data-description="Групповые восточные костюмы"         style="display:none">                </a>                    
                                
                                <a href="http://alinavgusarova.ru/">        <img alt="Групповые восточные костюмы"             src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-group-9.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-group-9.jpg"                 data-description="Групповые восточные костюмы"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Групповые восточные костюмы"             src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-group-11.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-group-11.jpg"                 data-description="Групповые восточные костюмы"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Групповые восточные костюмы"             src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-group-12.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-group-12.jpg"                 data-description="Групповые восточные костюмы"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Групповые восточные костюмы"             src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-group-13.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-group-13.jpg"                 data-description="Групповые восточные костюмы"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Групповые восточные костюмы"             src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-group-14.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-group-14.jpg"                 data-description="Групповые восточные костюмы"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Групповые восточные костюмы"             src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-group-16.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-group-16.jpg"                 data-description="Групповые восточные костюмы"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Групповые восточные костюмы"             src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-group-17.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-group-17.jpg"                 data-description="Групповые восточные костюмы"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Групповые восточные костюмы"             src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-group-21.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-group-21.jpg"                 data-description="Групповые восточные костюмы"         style="display:none">                </a>                        
                                <a href="http://alinavgusarova.ru/">        <img alt="Групповые восточные костюмы"             src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-group-18.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-group-18.jpg"                 data-description="Групповые восточные костюмы"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Групповые восточные костюмы"             src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-group-19.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-group-19.jpg"                 data-description="Групповые восточные костюмы"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Групповые восточные костюмы"             src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-group-20.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-group-20.jpg"                 data-description="Групповые восточные костюмы"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Групповые восточные костюмы"             src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-group-22.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-group-22.jpg"                 data-description="Групповые восточные костюмы"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Групповые восточные костюмы"             src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-group-37.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-group-37.jpg"                 data-description="Групповые восточные костюмы"         style="display:none">                </a>                        
                                <a href="http://alinavgusarova.ru/">        <img alt="Групповые восточные костюмы"             src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-group-1.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-group-1.jpg"                 data-description="Групповые восточные костюмы"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Групповые восточные костюмы"             src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-group-2.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-group-2.jpg"                 data-description="Групповые восточные костюмы"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Групповые восточные костюмы"             src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-group-23.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-group-23.jpg"                 data-description="Групповые восточные костюмы"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Групповые восточные костюмы"             src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-group-24.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-group-24.jpg"                 data-description="Групповые восточные костюмы"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Групповые восточные костюмы"             src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-group-25.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-group-25.jpg"                 data-description="Групповые восточные костюмы"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Групповые восточные костюмы"             src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-group-26.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-group-26.jpg"                 data-description="Групповые восточные костюмы"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Групповые восточные костюмы"             src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-group-27.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-group-27.jpg"                 data-description="Групповые восточные костюмы"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Групповые восточные костюмы"             src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-group-28.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-group-28.jpg"                 data-description="Групповые восточные костюмы"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Групповые восточные костюмы"             src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-group-29.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-group-29.jpg"                 data-description="Групповые восточные костюмы"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Групповые восточные костюмы"             src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-group-30.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-group-30.jpg"                 data-description="Групповые восточные костюмы"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Групповые восточные костюмы"             src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-group-31.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-group-31.jpg"                 data-description="Групповые восточные костюмы"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Групповые восточные костюмы"             src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-group-32.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-group-32.jpg"                 data-description="Групповые восточные костюмы"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Групповые восточные костюмы"             src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-group-33.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-group-33.jpg"                 data-description="Групповые восточные костюмы"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Групповые восточные костюмы"             src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-group-34.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-group-34.jpg"                 data-description="Групповые восточные костюмы"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Групповые восточные костюмы"             src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-group-40.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-group-40.jpg"                 data-description="Групповые восточные костюмы"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Групповые восточные костюмы"             src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-group-41.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-group-41.jpg"                 data-description="Групповые восточные костюмы"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Групповые восточные костюмы"             src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-group-42.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-group-42.jpg"                 data-description="Групповые восточные костюмы"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Групповые восточные костюмы"             src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-group-43.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-group-43.jpg"                 data-description="Групповые восточные костюмы"         style="display:none">                </a>
                            </div>  
                        </div> <!-- spoiler_body -->                  
                        <script type="text/javascript">
                            jQuery(document).ready(function(){
                                jQuery("#gallerybellydancegroup").unitegallery({
                                    carousel_space_between_tiles: 10,        /*space between tiles - расстояние между фотками в галерее*/
                                    carousel_autoplay: true,
                                    carousel_padding: 8,    
                                    theme_navigation_margin: 2, /*расстояние между фото и навигацией*/    
                                    tile_border_width: 4, /*толщина рамки в галерее*/
                                    tile_border_color:"#fff",    /*цвет рамки в галерее*/ 
                                });
                            });
                        </script>  