                        <div class="spoiler_links"> 
                            <h2>Сольные восточные костюмы (Альбом 3)</h2>
                        </div>
                        <div class="spoiler_body"> 
                            <div id="gallerybellydancesolo3" style="display:none;">
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-3-2.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-3-2.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-3-1.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-3-1.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>

                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-3-7.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-3-7.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-3-8.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-3-8.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-3-5.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-3-5.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-3-6.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-3-6.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>

                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-3-35.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-3-35.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-3-3.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-3-3.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-3-4.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-3-4.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>                                
                                
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-3-9.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-3-9.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-3-10.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-3-10.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-3-11.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-3-11.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-3-12.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-3-12.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                                
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-3-13.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-3-13.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-3-14.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-3-14.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-3-15.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-3-15.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-3-16.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-3-16.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                                
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-3-17.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-3-17.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-3-18.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-3-18.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                                
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-3-22.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-3-22.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-3-19.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-3-19.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-3-20.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-3-20.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-3-21.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-3-21.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                                                            
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-3-24.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-3-24.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-3-25.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-3-25.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-3-23.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-3-23.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                                
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-3-26.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-3-26.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-3-27.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-3-27.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                                
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-3-30.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-3-30.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-3-29.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-3-29.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-3-28.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-3-28.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                                
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-3-31.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-3-31.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-3-32.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-3-32.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-3-34.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-3-34.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                                
                                <a href="http://alinavgusarova.ru/">        <img alt="Сольный восточный костюмй"        src="http://alinavgusarova.ru/images/gallery/thumbs/bellydance-solo-3-33.jpg"        data-image="http://alinavgusarova.ru/images/gallery/big/bellydance-solo-3-33.jpg"        data-description="Сольный восточный костюмй"        style="display:none">        </a>
                            </div> 
                        </div> <!-- spoiler_body -->                   
                        <script type="text/javascript">
                            jQuery(document).ready(function(){
                                jQuery("#gallerybellydancesolo3").unitegallery({
                                    carousel_space_between_tiles: 10,        /*space between tiles - расстояние между фотками в галерее*/
                                    carousel_autoplay: true,
                                    carousel_padding: 8,     
                                    tile_border_width: 4, /*толщина рамки в галерее*/
                                    tile_border_color:"#fff",    /*цвет рамки в галерее*/ 
                                });
                            });
                        </script>        