                        <div class="spoiler_links">     
                            <h2>Свадебная одежда</h2>
                        </div> 
                        <div class="spoiler_body"> 
                            <div id="gallerywedding" style="display:none;">
                                <a href="http://alinavgusarova.ru/">        <img alt="Свадебный наряд"            src="http://alinavgusarova.ru/images/gallery/thumbs/wedding-22.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/wedding-22.jpg"             data-description="Свадебный наряд"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Свадебный наряд"             src="http://alinavgusarova.ru/images/gallery/thumbs/wedding-23.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/wedding-23.jpg"             data-description="Свадебный наряд"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Свадебный наряд"             src="http://alinavgusarova.ru/images/gallery/thumbs/wedding-24.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/wedding-24.jpg"             data-description="Свадебный наряд"         style="display:none">                </a>                    
                                <a href="http://alinavgusarova.ru/">        <img alt="Свадебный наряд"             src="http://alinavgusarova.ru/images/gallery/thumbs/wedding-17.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/wedding-17.jpg"             data-description="Свадебный наряд"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Свадебный наряд"             src="http://alinavgusarova.ru/images/gallery/thumbs/wedding-18.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/wedding-18.jpg"             data-description="Свадебный наряд"         style="display:none">                </a>                    
                                <a href="http://alinavgusarova.ru/">        <img alt="Свадебный наряд"             src="http://alinavgusarova.ru/images/gallery/thumbs/wedding-38.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/wedding-38.jpg"             data-description="Свадебный наряд"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Свадебный наряд"             src="http://alinavgusarova.ru/images/gallery/thumbs/wedding-35.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/wedding-35.jpg"             data-description="Свадебный наряд"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Свадебный наряд"             src="http://alinavgusarova.ru/images/gallery/thumbs/wedding-36.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/wedding-36.jpg"             data-description="Свадебный наряд"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Свадебный наряд"             src="http://alinavgusarova.ru/images/gallery/thumbs/wedding-37.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/wedding-37.jpg"             data-description="Свадебный наряд"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Свадебный наряд"             src="http://alinavgusarova.ru/images/gallery/thumbs/wedding-1.jpg"                 data-image="http://alinavgusarova.ru/images/gallery/big/wedding-1.jpg"                 data-description="Свадебный наряд"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Свадебный наряд"             src="http://alinavgusarova.ru/images/gallery/thumbs/wedding-2.jpg"                 data-image="http://alinavgusarova.ru/images/gallery/big/wedding-2.jpg"                 data-description="Свадебный наряд"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Свадебный наряд"             src="http://alinavgusarova.ru/images/gallery/thumbs/wedding-3.jpg"                 data-image="http://alinavgusarova.ru/images/gallery/big/wedding-3.jpg"                 data-description="Свадебный наряд"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Свадебный наряд"             src="http://alinavgusarova.ru/images/gallery/thumbs/wedding-4.jpg"                 data-image="http://alinavgusarova.ru/images/gallery/big/wedding-4.jpg"                 data-description="Свадебный наряд"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Свадебный наряд"             src="http://alinavgusarova.ru/images/gallery/thumbs/wedding-5.jpg"                 data-image="http://alinavgusarova.ru/images/gallery/big/wedding-5.jpg"                 data-description="Свадебный наряд"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Свадебный наряд"             src="http://alinavgusarova.ru/images/gallery/thumbs/wedding-6.jpg"                 data-image="http://alinavgusarova.ru/images/gallery/big/wedding-6.jpg"                 data-description="Свадебный наряд"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Свадебный наряд"             src="http://alinavgusarova.ru/images/gallery/thumbs/wedding-7.jpg"                 data-image="http://alinavgusarova.ru/images/gallery/big/wedding-7.jpg"                 data-description="Свадебный наряд"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Свадебный наряд"             src="http://alinavgusarova.ru/images/gallery/thumbs/wedding-12.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/wedding-12.jpg"             data-description="Свадебный наряд"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Свадебный наряд"             src="http://alinavgusarova.ru/images/gallery/thumbs/wedding-13.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/wedding-13.jpg"             data-description="Свадебный наряд"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Свадебный наряд"             src="http://alinavgusarova.ru/images/gallery/thumbs/wedding-14.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/wedding-14.jpg"             data-description="Свадебный наряд"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Свадебный наряд"             src="http://alinavgusarova.ru/images/gallery/thumbs/wedding-15.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/wedding-15.jpg"             data-description="Свадебный наряд"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Свадебный наряд"             src="http://alinavgusarova.ru/images/gallery/thumbs/wedding-16.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/wedding-16.jpg"             data-description="Свадебный наряд"         style="display:none">                </a>                        
                                <a href="http://alinavgusarova.ru/">        <img alt="Свадебный наряд"             src="http://alinavgusarova.ru/images/gallery/thumbs/wedding-8.jpg"                 data-image="http://alinavgusarova.ru/images/gallery/big/wedding-8.jpg"                 data-description="Свадебный наряд"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Свадебный наряд"             src="http://alinavgusarova.ru/images/gallery/thumbs/wedding-9.jpg"                 data-image="http://alinavgusarova.ru/images/gallery/big/wedding-9.jpg"                 data-description="Свадебный наряд"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Свадебный наряд"             src="http://alinavgusarova.ru/images/gallery/thumbs/wedding-10.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/wedding-10.jpg"             data-description="Свадебный наряд"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Свадебный наряд"             src="http://alinavgusarova.ru/images/gallery/thumbs/wedding-11.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/wedding-11.jpg"             data-description="Свадебный наряд"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Свадебный наряд"             src="http://alinavgusarova.ru/images/gallery/thumbs/wedding-19.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/wedding-19.jpg"             data-description="Свадебный наряд"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Свадебный наряд"             src="http://alinavgusarova.ru/images/gallery/thumbs/wedding-20.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/wedding-20.jpg"             data-description="Свадебный наряд"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Свадебный наряд"             src="http://alinavgusarova.ru/images/gallery/thumbs/wedding-21.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/wedding-21.jpg"             data-description="Свадебный наряд"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Свадебный наряд"             src="http://alinavgusarova.ru/images/gallery/thumbs/wedding-25.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/wedding-25.jpg"             data-description="Свадебный наряд"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Свадебный наряд"             src="http://alinavgusarova.ru/images/gallery/thumbs/wedding-26.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/wedding-26.jpg"             data-description="Свадебный наряд"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Свадебный наряд"             src="http://alinavgusarova.ru/images/gallery/thumbs/wedding-27.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/wedding-27.jpg"             data-description="Свадебный наряд"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Свадебный наряд"             src="http://alinavgusarova.ru/images/gallery/thumbs/wedding-28.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/wedding-28.jpg"             data-description="Свадебный наряд"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Свадебный наряд"             src="http://alinavgusarova.ru/images/gallery/thumbs/wedding-29.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/wedding-29.jpg"             data-description="Свадебный наряд"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Свадебный наряд"             src="http://alinavgusarova.ru/images/gallery/thumbs/wedding-30.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/wedding-30.jpg"             data-description="Свадебный наряд"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Свадебный наряд"             src="http://alinavgusarova.ru/images/gallery/thumbs/wedding-31.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/wedding-31.jpg"             data-description="Свадебный наряд"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Свадебный наряд"             src="http://alinavgusarova.ru/images/gallery/thumbs/wedding-32.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/wedding-32.jpg"             data-description="Свадебный наряд"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Свадебный наряд"             src="http://alinavgusarova.ru/images/gallery/thumbs/wedding-33.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/wedding-33.jpg"             data-description="Свадебный наряд"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Свадебный наряд"             src="http://alinavgusarova.ru/images/gallery/thumbs/wedding-34.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/wedding-34.jpg"             data-description="Свадебный наряд"         style="display:none">                </a>
                            </div> 
                        </div> <!-- spoiler_body -->                   
                        <script type="text/javascript">
                            jQuery(document).ready(function(){
                                jQuery("#gallerywedding").unitegallery({
                                    carousel_space_between_tiles: 10,        /*space between tiles - расстояние между фотками в галерее*/
                                    carousel_autoplay: true,
                                    carousel_padding: 8,     
                                    theme_navigation_margin: 2, /*расстояние между фото и навигацией*/   
                                    tile_border_width: 4, /*толщина рамки в галерее*/
                                    tile_border_color:"#fff",    /*цвет рамки в галерее*/ 
                                });
                            });
                        </script>    