                        <div class="spoiler_links"> 
                            <h2>Нарядная одежда</h2>
                        </div>  
                        <div class="spoiler_body">
                            <div id="galleryelegant" style="display:none;">
                                <a href="http://alinavgusarova.ru/">        <img alt="Нарядная одежда"             src="http://alinavgusarova.ru/images/gallery/thumbs/elegant-1.jpg"                 data-image="http://alinavgusarova.ru/images/gallery/big/elegant-1.jpg"                 data-description="Нарядная одежда"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Нарядная одежда"             src="http://alinavgusarova.ru/images/gallery/thumbs/elegant-2.jpg"                 data-image="http://alinavgusarova.ru/images/gallery/big/elegant-2.jpg"                 data-description="Нарядная одежда"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Нарядная одежда"             src="http://alinavgusarova.ru/images/gallery/thumbs/elegant-3.jpg"                 data-image="http://alinavgusarova.ru/images/gallery/big/elegant-3.jpg"                 data-description="Нарядная одежда"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Нарядная одежда"             src="http://alinavgusarova.ru/images/gallery/thumbs/elegant-4.jpg"                 data-image="http://alinavgusarova.ru/images/gallery/big/elegant-4.jpg"                 data-description="Нарядная одежда"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Нарядная одежда"             src="http://alinavgusarova.ru/images/gallery/thumbs/elegant-5.jpg"                 data-image="http://alinavgusarova.ru/images/gallery/big/elegant-5.jpg"                 data-description="Нарядная одежда"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Нарядная одежда"             src="http://alinavgusarova.ru/images/gallery/thumbs/elegant-6.jpg"                 data-image="http://alinavgusarova.ru/images/gallery/big/elegant-6.jpg"                 data-description="Нарядная одежда"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Нарядная одежда"             src="http://alinavgusarova.ru/images/gallery/thumbs/elegant-7.jpg"                 data-image="http://alinavgusarova.ru/images/gallery/big/elegant-7.jpg"                 data-description="Нарядная одежда"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Нарядная одежда"             src="http://alinavgusarova.ru/images/gallery/thumbs/elegant-8.jpg"                 data-image="http://alinavgusarova.ru/images/gallery/big/elegant-8.jpg"                 data-description="Нарядная одежда"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Нарядная одежда"             src="http://alinavgusarova.ru/images/gallery/thumbs/elegant-9.jpg"                 data-image="http://alinavgusarova.ru/images/gallery/big/elegant-9.jpg"                 data-description="Нарядная одежда"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Нарядная одежда"             src="http://alinavgusarova.ru/images/gallery/thumbs/elegant-10.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/elegant-10.jpg"             data-description="Нарядная одежда"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Нарядная одежда"             src="http://alinavgusarova.ru/images/gallery/thumbs/elegant-11.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/elegant-11.jpg"             data-description="Нарядная одежда"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Нарядная одежда"             src="http://alinavgusarova.ru/images/gallery/thumbs/elegant-12.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/elegant-12.jpg"             data-description="Нарядная одежда"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Нарядная одежда"             src="http://alinavgusarova.ru/images/gallery/thumbs/elegant-13.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/elegant-13.jpg"             data-description="Нарядная одежда"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Нарядная одежда"             src="http://alinavgusarova.ru/images/gallery/thumbs/elegant-14.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/elegant-14.jpg"             data-description="Нарядная одежда"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Нарядная одежда"             src="http://alinavgusarova.ru/images/gallery/thumbs/elegant-15.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/elegant-15.jpg"             data-description="Нарядная одежда"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Нарядная одежда"             src="http://alinavgusarova.ru/images/gallery/thumbs/elegant-16.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/elegant-16.jpg"             data-description="Нарядная одежда"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Нарядная одежда"             src="http://alinavgusarova.ru/images/gallery/thumbs/elegant-17.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/elegant-17.jpg"             data-description="Нарядная одежда"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Нарядная одежда"             src="http://alinavgusarova.ru/images/gallery/thumbs/elegant-18.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/elegant-18.jpg"             data-description="Нарядная одежда"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Нарядная одежда"             src="http://alinavgusarova.ru/images/gallery/thumbs/elegant-19.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/elegant-19.jpg"             data-description="Нарядная одежда"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Нарядная одежда"             src="http://alinavgusarova.ru/images/gallery/thumbs/elegant-20.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/elegant-20.jpg"             data-description="Нарядная одежда"         style="display:none">                </a>
                            </div>
                        </div> <!-- spoiler_body -->
                        <script type="text/javascript">
                            jQuery(document).ready(function(){
                                jQuery("#galleryelegant").unitegallery({
                                    carousel_space_between_tiles: 10,        /*space between tiles - расстояние между фотками в галерее*/
                                    carousel_autoplay: true,
                                    carousel_padding: 8,     
                                    theme_navigation_margin: 2, /*расстояние между фото и навигацией*/    
                                    tile_border_width: 4, /*толщина рамки в галерее*/
                                    tile_border_color:"#fff",    /*цвет рамки в галерее*/ 
                                });
                            });
                        </script>   