                        <div class="spoiler_links"> 
                            <h2>Костюмы для шоу</h2>
                        </div>
                        <div class="spoiler_body"> 
                            <div id="galleryshow" style="display:none;">
                                <a href="http://alinavgusarova.ru/">        <img alt="Школьная форма"             src="http://alinavgusarova.ru/images/gallery/thumbs/show-21.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/show-21.jpg"                 data-description="Костюмы для шоу"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Школьная форма"             src="http://alinavgusarova.ru/images/gallery/thumbs/show-20.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/show-20.jpg"                 data-description="Костюмы для шоу"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Школьная форма"             src="http://alinavgusarova.ru/images/gallery/thumbs/show-19.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/show-19.jpg"                 data-description="Костюмы для шоу"         style="display:none">                </a>
                                
                                <a href="http://alinavgusarova.ru/">        <img alt="Школьная форма"             src="http://alinavgusarova.ru/images/gallery/thumbs/show-1.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/show-1.jpg"                 data-description="Костюмы для шоу"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Школьная форма"             src="http://alinavgusarova.ru/images/gallery/thumbs/show-2.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/show-2.jpg"                 data-description="Костюмы для шоу"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Школьная форма"             src="http://alinavgusarova.ru/images/gallery/thumbs/show-3.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/show-3.jpg"                 data-description="Костюмы для шоу"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Школьная форма"             src="http://alinavgusarova.ru/images/gallery/thumbs/show-4.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/show-4.jpg"                 data-description="Костюмы для шоу"         style="display:none">                </a>
                                
                                <a href="http://alinavgusarova.ru/">        <img alt="Школьная форма"             src="http://alinavgusarova.ru/images/gallery/thumbs/show-10.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/show-10.jpg"                 data-description="Костюмы для шоу"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Школьная форма"             src="http://alinavgusarova.ru/images/gallery/thumbs/show-11.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/show-11.jpg"                 data-description="Костюмы для шоу"         style="display:none">                </a>
                                
                                <a href="http://alinavgusarova.ru/">        <img alt="Школьная форма"             src="http://alinavgusarova.ru/images/gallery/thumbs/show-12.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/show-12.jpg"                 data-description="Костюмы для шоу"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Школьная форма"             src="http://alinavgusarova.ru/images/gallery/thumbs/show-13.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/show-13.jpg"                 data-description="Костюмы для шоу"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Школьная форма"             src="http://alinavgusarova.ru/images/gallery/thumbs/show-14.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/show-14.jpg"                 data-description="Костюмы для шоу"         style="display:none">                </a>
                                
                                <a href="http://alinavgusarova.ru/">        <img alt="Школьная форма"             src="http://alinavgusarova.ru/images/gallery/thumbs/show-5.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/show-5.jpg"                 data-description="Костюмы для шоу"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Школьная форма"             src="http://alinavgusarova.ru/images/gallery/thumbs/show-6.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/show-6.jpg"                 data-description="Костюмы для шоу"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Школьная форма"             src="http://alinavgusarova.ru/images/gallery/thumbs/show-7.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/show-7.jpg"                 data-description="Костюмы для шоу"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Школьная форма"             src="http://alinavgusarova.ru/images/gallery/thumbs/show-8.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/show-8.jpg"                 data-description="Костюмы для шоу"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Школьная форма"             src="http://alinavgusarova.ru/images/gallery/thumbs/show-9.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/show-9.jpg"                 data-description="Костюмы для шоу"         style="display:none">                </a>
                                
                                <a href="http://alinavgusarova.ru/">        <img alt="Школьная форма"             src="http://alinavgusarova.ru/images/gallery/thumbs/show-16.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/show-16.jpg"                 data-description="Костюмы для шоу"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Школьная форма"             src="http://alinavgusarova.ru/images/gallery/thumbs/show-17.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/show-17.jpg"                 data-description="Костюмы для шоу"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Школьная форма"             src="http://alinavgusarova.ru/images/gallery/thumbs/show-18.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/show-18.jpg"                 data-description="Костюмы для шоу"         style="display:none">                </a>
                                
                                <a href="http://alinavgusarova.ru/">        <img alt="Школьная форма"             src="http://alinavgusarova.ru/images/gallery/thumbs/show-22.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/show-22.jpg"                 data-description="Костюмы для шоу"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Школьная форма"             src="http://alinavgusarova.ru/images/gallery/thumbs/show-23.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/show-23.jpg"                 data-description="Костюмы для шоу"         style="display:none">                </a>
                                
                                <a href="http://alinavgusarova.ru/">        <img alt="Школьная форма"             src="http://alinavgusarova.ru/images/gallery/thumbs/show-24.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/show-24.jpg"                 data-description="Костюмы для шоу"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Школьная форма"             src="http://alinavgusarova.ru/images/gallery/thumbs/show-15.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/show-15.jpg"                 data-description="Костюмы для шоу"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Школьная форма"             src="http://alinavgusarova.ru/images/gallery/thumbs/show-27.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/show-27.jpg"                 data-description="Костюмы для шоу"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Школьная форма"             src="http://alinavgusarova.ru/images/gallery/thumbs/show-28.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/show-28.jpg"                 data-description="Костюмы для шоу"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Школьная форма"             src="http://alinavgusarova.ru/images/gallery/thumbs/show-39.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/show-39.jpg"                 data-description="Костюмы для шоу"         style="display:none">                </a>
                                
                                <a href="http://alinavgusarova.ru/">        <img alt="Школьная форма"             src="http://alinavgusarova.ru/images/gallery/thumbs/show-25.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/show-25.jpg"                 data-description="Костюмы для шоу"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Школьная форма"             src="http://alinavgusarova.ru/images/gallery/thumbs/show-33.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/show-33.jpg"                 data-description="Костюмы для шоу"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Школьная форма"             src="http://alinavgusarova.ru/images/gallery/thumbs/show-29.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/show-29.jpg"                 data-description="Костюмы для шоу"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Школьная форма"             src="http://alinavgusarova.ru/images/gallery/thumbs/show-30.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/show-30.jpg"                 data-description="Костюмы для шоу"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Школьная форма"             src="http://alinavgusarova.ru/images/gallery/thumbs/show-31.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/show-31.jpg"                 data-description="Костюмы для шоу"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Школьная форма"             src="http://alinavgusarova.ru/images/gallery/thumbs/show-32.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/show-32.jpg"                 data-description="Костюмы для шоу"         style="display:none">                </a>
                                
                                <a href="http://alinavgusarova.ru/">        <img alt="Школьная форма"             src="http://alinavgusarova.ru/images/gallery/thumbs/show-26.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/show-26.jpg"                 data-description="Костюмы для шоу"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Школьная форма"             src="http://alinavgusarova.ru/images/gallery/thumbs/show-40.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/show-40.jpg"                 data-description="Костюмы для шоу"         style="display:none">                </a>  
                                                                                                                                                                                                                                                                                                                                                                                                          
                                <a href="http://alinavgusarova.ru/">        <img alt="Школьная форма"             src="http://alinavgusarova.ru/images/gallery/thumbs/show-37.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/show-37.jpg"                 data-description="Костюмы для шоу"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Школьная форма"             src="http://alinavgusarova.ru/images/gallery/thumbs/show-38.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/show-38.jpg"                 data-description="Костюмы для шоу"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Школьная форма"             src="http://alinavgusarova.ru/images/gallery/thumbs/show-34.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/show-34.jpg"                 data-description="Костюмы для шоу"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Школьная форма"             src="http://alinavgusarova.ru/images/gallery/thumbs/show-35.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/show-35.jpg"                 data-description="Костюмы для шоу"         style="display:none">                </a>
                                <a href="http://alinavgusarova.ru/">        <img alt="Школьная форма"             src="http://alinavgusarova.ru/images/gallery/thumbs/show-36.jpg"             data-image="http://alinavgusarova.ru/images/gallery/big/show-36.jpg"                 data-description="Костюмы для шоу"         style="display:none">                </a>
                                
                            </div> 
                        </div> <!-- spoiler_body -->                   
                        <script type="text/javascript">
                            jQuery(document).ready(function(){
                                jQuery("#galleryshow").unitegallery({
                                    carousel_space_between_tiles: 10,        /*space between tiles - расстояние между фотками в галерее*/
                                    carousel_autoplay: true,
                                    carousel_padding: 8, 
                                    theme_navigation_margin: 2, /*расстояние между фото и навигацией*/        
                                    tile_border_width: 4, /*толщина рамки в галерее*/
                                    tile_border_color:"#fff",    /*цвет рамки в галерее*/ 
                                });
                            });
                        </script>                        
